**importing libray**

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
v=np.array([1,2,3])

In [4]:
v

array([1, 2, 3])

In [5]:
v[0:2]

array([1, 2])

In [39]:
np.arange(10,0)


array([], dtype=int64)

In [7]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [8]:
g=np.array([1,2,3,4,5,6,6])

In [9]:
print(g)

[1 2 3 4 5 6 6]


In [10]:
np.delete(g,5)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.power(g,4)

array([   1,   16,   81,  256,  625, 1296, 1296])